version: "3.9"

services:
    client:
        depends_on:
            - server
        build: ./client
        ports:
            - 80:80

    server:
        depends_on:
            - db
        build: ./server
        ports:
            - 8000:8000
        environment:
            MONGO_URI: mongodb://db/hitly

    db:
        image: mongo:4.0.16-xenial
        ports:
            - 27017:27017
        volumes:
            - hitly:/data/db

volumes:
    hitly:
